# Generated by Django 5.0.7 on 2024-08-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_rename_post_posting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='author',
        ),
    ]
