# Generated by Django 5.0.7 on 2024-08-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_remove_posting_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
