# Generated by Django 5.0.7 on 2024-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0004_alter_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
