# Generated by Django 5.0.7 on 2024-08-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0006_alter_posting_text_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
