# Generated by Django 5.0.7 on 2024-08-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0008_alter_books_link_alter_posting_text_conclusion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
