# Generated by Django 5.0.7 on 2024-08-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0010_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book',
            new_name='books',
        ),
    ]
