# Generated by Django 5.0.7 on 2024-08-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0011_rename_book_books_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='books',
            new_name='book',
        ),
    ]
