# Generated by Django 5.0.7 on 2024-08-01 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0012_rename_books_books_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AddField(
            model_name='posting',
            name='book',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posting',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
