# Generated by Django 5.0.7 on 2024-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0013_delete_books_posting_book_posting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='book',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posting',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(default='bla', max_length=30),
        ),
    ]
