# Generated by Django 5.0.7 on 2024-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0014_alter_posting_book_alter_posting_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='book',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='link',
        ),
    ]
