# Generated by Django 5.0.7 on 2024-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0016_alter_posting_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
