# Generated by Django 5.0.7 on 2024-08-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0018_posting_book_posting_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
