# Generated by Django 5.0.7 on 2024-08-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0019_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='book',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='link',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
