# Generated by Django 5.0.7 on 2024-08-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0020_alter_posting_book_alter_posting_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=10, null=True)),
                ('link', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posting',
            name='book',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='link',
        ),
    ]
