# Generated by Django 5.0.7 on 2024-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0021_books_remove_posting_book_remove_posting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
