# Generated by Django 5.0.7 on 2024-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0022_alter_posting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='text_conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='text_development',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='text_introdution',
            field=models.TextField(null=True),
        ),
    ]
