# Generated by Django 5.0.7 on 2024-08-01 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0023_alter_posting_text_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
