# Generated by Django 5.0.7 on 2024-08-01 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0025_alter_posting_text_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
