# Generated by Django 5.0.7 on 2024-08-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0026_alter_posting_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posting',
        ),
    ]
